fullname: manga-checker-box-dev

image:
  tag: "development"
  pullPolicy: Always

secret:
  name: "manga-checker-box-dev"

persistence:
  enabled: true
  storageClass: "microk8s-hostpath" 
  size: 10Mi
  accessModes:
    - ReadWriteOnce
  mountPath: /db
  dbFilename: manga_tracker_dev.db

# Save backups database
cronjob:
  enabled: true
  name: sqlite-backup-nfs-dev
  schedule: "30 0 * * *"   # Todos los días a las 00:30 AM
  server_ip: qnap.boxhomelab.com
  nfs_path: /SQLite
  storage: 10Mi