apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  annotations:
    "helm.sh/resource-policy": keep #  Helm solo desplegara los secretos la primera vez. En proximos desliegues no borrara el contenido configurado en kubernetes
type: Opaque
stringData:
  ADMIN_TELEGRAM_ID: ""
  MANGA_CHECKER_BOX_PASSWD: ""
  MANGA_CHECKER_BOX_TOKEN: ""
